server:
  port: 9090
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    mongodb:
      uri: mongodb+srv://assignmentsolver:865PlejVOMNaJ3fN@assignmentsolver.69t4m.mongodb.net/AssignmentSolver?retryWrites=true&w=majority&ssl=true
      database: AssignmentSolver
    rest:
      base-path: /
    cassandra:
      request:
        timeout: 10s
#  data:
#    mongodb:
#      database: assignmentStore
#      host: localhost
#      port: 27017
#      repositories:
#        type: auto
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    user:
      name: foo
      password: foo
      roles:
        - ADMIN
        - USER
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    date-format: "dd-MM-yyyy"
    serialization:
      write_dates_as_timestamps: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: sltechprimers@gmail.com
    password: jusffbeiplhwryth
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
client:
  validity:
    time: 36000
upload:
  dir: /resources




